"""Protocol layer for ITU-R M.493-16 DSC."""

from .constants import (
    VHF_MARK_FREQ, VHF_SPACE_FREQ, VHF_BAUD_RATE, VHF_CHANNEL_70_FREQ,
    INTERNAL_SAMPLE_RATE,
)
from .symbols import (
    FormatSpecifier, CategoryOfCall, NatureOfDistress,
    FirstTelecommand, SecondTelecommand, EndOfSequence,
    SYM_DISTRESS, SYM_ALL_SHIPS, SYM_GROUP, SYM_INDIVIDUAL,
    SYM_GEO_AREA, SYM_INDIVIDUAL_AUTO,
    SYM_CAT_DISTRESS, SYM_CAT_URGENCY, SYM_CAT_SAFETY, SYM_CAT_ROUTINE,
    SYM_NATURE_FIRE, SYM_NATURE_FLOODING, SYM_NATURE_COLLISION,
    SYM_NATURE_GROUNDING, SYM_NATURE_LISTING, SYM_NATURE_SINKING,
    SYM_NATURE_DISABLED, SYM_NATURE_UNDESIGNATED, SYM_NATURE_ABANDONING,
    SYM_NATURE_PIRACY, SYM_NATURE_MAN_OVERBOARD,
    SYM_TC1_F3E_G3E_ALL, SYM_TC1_F3E_G3E_DUPLEX, SYM_TC1_POLLING,
    SYM_TC1_UNABLE_COMPLY, SYM_TC1_END_OF_CALL, SYM_TC1_DATA,
    SYM_TC1_J3E_TP, SYM_TC1_DISTRESS_ACK, SYM_TC1_DISTRESS_RELAY,
    SYM_TC1_F1B_J2B_TTY_FEC, SYM_TC1_F1B_J2B_TTY_ARQ, SYM_TC1_TEST,
    SYM_TC2_NO_INFO, SYM_TC2_NO_REASON, SYM_TC2_CONGESTION, SYM_TC2_BUSY,
    SYM_TC2_QUEUE, SYM_TC2_STATION_BARRED, SYM_TC2_NO_OPERATOR,
    SYM_TC2_OP_TEMP_UNAVAIL, SYM_TC2_EQUIP_DISABLED, SYM_TC2_UNABLE_CHANNEL,
    SYM_TC2_UNABLE_MODE, SYM_TC2_SHIPS_AIRCRAFT, SYM_TC2_MEDICAL,
    SYM_TC2_PAY_PHONE, SYM_TC2_FACSIMILE,
    SYM_EOS_ACK_RQ, SYM_EOS_ACK_BQ, SYM_EOS_EOT,
    SYM_PHASING_DX, SYM_PHASING_RX,
    SYM_NO_INFO, SYM_WILDCARD,
    DOT_PATTERN_BITS_VHF, DOT_PATTERN_BITS_HF_MF,
    TIME_DIVERSITY_SPREAD,
)
from .characters import (
    encode_char, decode_char, encode_bitstream, decode_bitstream,
    code_to_bits, bits_to_code, hamming_distance, CHARACTER_TABLE,
)
from .error_correction import compute_ecc, verify_ecc, extract_info_symbols
from .mmsi import MMSI, MMSIType
from .position import Position, encode_position, decode_position, encode_time_utc, decode_time_utc
